BookShop/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from store.views import UserList,UserRUD

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('',include("store.urls")),
    path('users/',UserList.as_view()),
    path('user/<int:pk>',UserRUD.as_view()),

   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:bookid>', views.cart_add, name='cart_add'),
	path('remove/<int:bookid>', views.cart_remove, name='cart_remove'),
	path('update/<int:bookid>/<int:quantity>', views.cart_update, name='cart_update'),
]

BookShop/store/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns




app_name = 'store'

urlpatterns = [
	path('', views.index, name = "index"),
	path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),
	path('book/<int:id>', views.get_book, name="book"),
	path('books', views.get_books, name="books"),
	path('category/<int:id>', views.get_book_category, name="category"),
	path('writer/<int:id>', views.get_writer, name = "writer"),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>', views.UserDetail.as_view()),
    path('bookdetail/', views.BookDetail.as_view(), name='book_list'),
    path('receive_message/', views.receive_message, name='receive_message'),
    


    

]

urlpatterns = format_suffix_patterns(urlpatterns)

BookShop/store/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
	name = models.CharField(max_length = 100)
	slug = models.SlugField(max_length = 150, unique=True ,db_index=True)
	icon = models.FileField(upload_to = "category/")
	create_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.name

class Writer(models.Model):
	name = models.CharField(max_length = 100)
	slug = models.SlugField(max_length=150, unique=True ,db_index=True)
	bio = models.TextField()
	pic = models.FileField(upload_to = "writer/")
	create_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.name

class Book(models.Model):
	writer = models.ForeignKey(Writer, on_delete = models.CASCADE)
	category = models.ForeignKey(Category, on_delete = models.CASCADE)
	name = models.CharField(max_length = 100)
	slug = models.SlugField(max_length=100, db_index=True)
	price = models.IntegerField()
	stock = models.IntegerField()
	coverpage = models.FileField(upload_to = "coverpage/")
	bookpage = models.FileField(upload_to = "bookpage/")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	totalreview = models.IntegerField(default=1)
	totalrating = models.IntegerField(default=5)
	status = models.IntegerField(default=0)
	description = models.TextField()

	def __str__(self):
	    return self.name

class Review(models.Model):
	customer = models.ForeignKey(User, on_delete = models.CASCADE)
	book = models.ForeignKey(Book, on_delete = models.CASCADE)
	review_star = models.IntegerField()
	review_text = models.TextField()
	created = models.DateTimeField(auto_now_add=True)

class Slider(models.Model):
	title = models.CharField(max_length=150)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	slideimg = models.FileField(upload_to = "slide/")

	def __str__(self):
		return self.title

BookShop/store/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Review

class RegistrationForm(UserCreationForm):
    name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = [
            'name',
            'email',
            'username',
            'password1',
            'password2'
        ]
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class ReviewForm(forms.ModelForm):
    review_star = forms.IntegerField(widget=forms.HiddenInput(), initial=1)
    review_text = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write Your Review'}))

    class Meta:
        model = Review
        fields = [
            'review_star',
            'review_text'
        ]
    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    

BookShop/store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import Category, Writer, Book, Review, Slider
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .forms import RegistrationForm, ReviewForm
from rest_framework import generics
from . import serializers





def index(request):
    newpublished = Book.objects.order_by('-created')[:15]
    slide = Slider.objects.order_by('-created')[:3]
    context = {
        "newbooks":newpublished,
        "slide": slide
    }
    return render(request, 'store/index.html', context)


def signin(request):
    if request.user.is_authenticated:
        return redirect('store:index')
    else:
        if request.method == "POST":
            user = request.POST.get('user')
            password = request.POST.get('pass')
            auth = authenticate(request, username=user, password=password)
            if auth is not None:
                login(request, auth)
                return redirect('store:index')
            else:
            	messages.error(request, 'username and password doesn\'t match')
        
        return render(request, "store/login.html")	


def signout(request):
    logout(request)
    return redirect('store:index')	


def registration(request):
	form = RegistrationForm(request.POST or None)
	if form.is_valid():
		form.save()
		return redirect('store:signin')

	return render(request, 'store/signup.html', {"form": form})

def payment(request):
    return render(request, 'store/payment.html')


def get_book(request, id):
    form = ReviewForm(request.POST or None)
    book = get_object_or_404(Book, id=id)
    rbooks = Book.objects.filter(category_id=book.category.id)
    r_review = Review.objects.filter(book_id=id).order_by('-created')

    paginator = Paginator(r_review, 4)
    page = request.GET.get('page')
    rreview = paginator.get_page(page)

    if request.method == 'POST':
        if request.user.is_authenticated:
            if form.is_valid():
                temp = form.save(commit=False)
                temp.customer = User.objects.get(id=request.user.id)
                temp.book = book          
                temp = Book.objects.get(id=id)
                temp.totalreview += 1
                temp.totalrating += int(request.POST.get('review_star'))
                form.save()  
                temp.save()

                messages.success(request, "Review Added Successfully")
                form = ReviewForm()
        else:
            messages.error(request, "You need login first.")
    context = {
        "book":book,
        "rbooks": rbooks,
        "form": form,
        "rreview": rreview
    }
    return render(request, "store/book.html", context)


def get_books(request):
    books_ = Book.objects.all().order_by('-created')
    paginator = Paginator(books_, 10)
    page = request.GET.get('page')
    books = paginator.get_page(page)
    return render(request, "store/category.html", {"book":books})

def get_book_category(request, id):
    book_ = Book.objects.filter(category_id=id)
    paginator = Paginator(book_, 10)
    page = request.GET.get('page')
    book = paginator.get_page(page)
    return render(request, "store/category.html", {"book":book})

def get_writer(request, id):
    wrt = get_object_or_404(Writer, id=id)
    book = Book.objects.filter(writer_id=wrt.id)
    context = {
        "wrt": wrt,
        "book": book
    }
    return render(request, "store/writer.html", context)



class UserList(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer
    
class UserRUD(generics.RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer


class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = serializers.UserSerializer


class BookDetail(generics.ListAPIView):
    queryset = Book.objects.all()
    serializer_class = serializers.BookSerializer


def receive_message(request):
    import requests, json
    data = requests.get('http://127.0.0.1:8000/users/')
    context = {
        'data': data.json(),
    }
    print("Data: ", data.json())
    return render(request,'store/show_data.html', context)


#'store/show_data.html',

BookShop/store/templates/store/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Real Madrid Store</title>
	{% load static %}
	<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/skdslider.css' %}"> 
</head>
<body>
<div class="pre_loader gray_bg text-center">
    <div class="loader">
        <div><div><div><div></div></div></div></div>
    </div>
</div>
{% include 'store/bin/header.html' %}

{% block headermenu %} {% endblock %}

<div class="container-fluid">
	<div class="row">
		<div class="col-sm-2">
			{% include 'store/bin/sidebar.html' %}
		</div>
		<div class="col-sm-10">
			{% block container %}{% endblock %}
		</div>
		
	</div>
</div>
<div id="snackbar"></div>

{% include 'store/bin/footer.html' %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-touchspin/4.2.5/jquery.bootstrap-touchspin.js" type="text/javascript"></script>
<script src="{% static 'js/skdslider.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Readmore.js/2.2.1/readmore.js" type="text/javascript"></script>
<script src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script>
<script src="{% static 'js/main.js' %}"></script> 
{% block scripts %}{% endblock %}
</body>
</html>

BookShop/store/templates/store/book.html
{% extends 'store/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load customfunction %}
{% block container %}
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-3">
							<div class="grid-item">
								<div class="view-details" style="cursor:pointer">
									<img id="product_image" class="lookInsideImg" src="{{ book.coverpage.url }}">
								</div>
							</div>	
							<div class="lookInsideDiv" style="display: none;">
								<div class="exitBtn"></div>
								<div class="pagesArea">
									<ul class="list-unstyled pages">
										<li><img src="{{ book.bookpage.url }}"></li>
									</ul>
								</div>
							</div>				
						</div>
						
						<div class="col-sm-6">
							<div class="product-information">
								<h4>{{ book.name }}</h4>
								<p style="margin: 0px">туралы <a style="font-weight:bold" href="{% url 'store:writer' id=book.writer.id %}">{{ book.writer }}</a></p>
								<div class='rating'>
									{{ book.totalrating|averagerating:book.totalreview }}
									<a href='#getreview'><span class='totalrating'>{{ book.totalreview|add:-1 }} Пікірлер</span></a>
								</div>
								<article class="text-justify" style="margin-top:10px;">
									{{ book.description }}
								</article>

							</div>
						</div>
						<div class="col-sm-3">
							<div class="pricebox">
								<p>Бағасы: ₸. <span> {{ book.price }}</span></p>
								<button class="btn btn-warning" id="addTocart" data-book-id="{{ book.id }}">
									<i class="fa fa-shopping-cart"></i>Себетке қосу
								</button>
							</div>
						</div>
					</div>	
				</div>

			    <div class="col-sm-9 mt-5" id="getreview">
					{% if messages %}
						<div class="messages">
						    {% for message in messages %}
						    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
						    {% endfor %}
						</div>
					{% endif %}	
					<div class="rating-stars text-left">
						<ul id="stars">
						  <li id="azaa" class="star" data-value="1"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azbb" class="star" data-value="2"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azcc" class="star" data-value="3"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azdd" class="star" data-value="4"> <i class="fa fa-star fa-fw"></i> </li>
						  <li id="azee" class="star" data-value="5"> <i class="fa fa-star fa-fw"></i> </li>
						</ul>
					</div>		
				   <form action="" method="POST" class="needs-validation" novalidate="">
				   	{% csrf_token %}
					
						<div class="form-group">
							{{ form.review_star|as_crispy_field }}
						</div>
						<div class="form-group">
							{{ form.review_text|as_crispy_field }}
						</div>
						<div class="form-group">
							<button class="btn btn-warning" type="submit" style="color: #fff">Ұсыну</button>
						</div>
				   </form>	
					{% for lreview in rreview %}
					<div class="card">
						<div class="card-body">
							<img src="{% static 'images/profile.png' %}"/>
							<b> {{ lreview.customer }} </b>
							<div class='rating'>
								{{ lreview.review_star|averagerating:1 }}
							</div>
							<div class="given_review_date">
								<span style="color:#555;"> {{ lreview.created }}</span>
							</div>
							<p style="margin-top: 10px"> {{ lreview.review_text }} </p>
						 </div>
					</div>
					{% endfor %}
					
					<div class="d-pagination">
					    <ul class="pagination">
						{% if rreview.has_previous %}
							<li class="page-item">
								<a class="page-link" href="?page=1">First</a>
							</li>								
							<li class="page-item">
								<a class="page-link" href="?page={{ rreview.previous_page_number }}">Алдыңғы</a>
							</li>
						{% endif %}
						{% for ord in rreview.paginator.page_range %}
							{% if rreview.number == ord %}
								<li class="page-item active">
									<span class="page-link">{{ ord }}
										<span class="sr-only">(current)</span>
									</span>
								</li>
							{% elif ord > rreview.number|add:'-3' and ord < rreview.number|add:'3' %}
								<li class="page-item">
									<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
								</li>

							{% endif %}

						{% endfor %}
						 {% if rreview.has_next %}
							<li class="page-item">
								<a class="page-link" href="?page={{ rreview.next_page_number }}">Келесі</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="?page={{ rreview.paginator.num_pages }}">Алдыңғы</a>
							</li>
						{% endif %}
					    </ul>
					</div>		
				</div>
			</div>

{% endblock %}


{% block scripts %}
<script type="text/javascript">
	$(document).on('ready', function() {
		$(document).on('click', '.lookInsideImg,.lookInsideBg', function (e) {
			$('div.overlay').fadeIn(500);
			$('div.lookInsideDiv').fadeIn(500);
		});
	   
	   $(document).on('click', 'div.lookInsideDiv div.exitBtn', function () {
			$('div.overlay').fadeOut(500);
			$('div.lookInsideDiv').fadeOut(500);
			refCaro($('#bookDR99'));
		});
		$(document).on('click', 'div.overlay', function () {
			$('div.overlay').fadeOut(500);
			$('div.lookInsideDiv').fadeOut(500);
			refCaro($('#bookDR99'));
			return false
		});	
	});
</script>

{% endblock %}

BookShop/store/templates/store/category.html
{% extends 'store/base.html' %}
{% load customfunction %}
{% block container %}
			<div class="row">
				{% for item in book %}
				<div class = 'col-sm-3'>
					<div class="book-wrapper text-center">
						<div class="coverpage">
							<img src="{{ item.coverpage.url }}"/>
						</div>
						<a href="{% url 'store:book' id=item.id %}">{{ item.name }}</a>
						<a href="{% url 'store:writer'  id=item.writer.id %}">{{ item.writer }}</a>
						<div class="rating">
							{{ item.totalrating|averagerating:item.totalreview }}
							<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
						</div>
						<p> {{ item.price }} $ </p>
						<button class="btn btn-warning" id="addTocart" data-book-id="{{ item.id }}">
								<i class="fa fa-shopping-cart"></i> Себетке қосу
						</button>
					</div>
				</div>
				{% endfor %}

			</div>
			{% if book|length > 0 %}
			<div class="d-pagination">
			    <ul class="pagination">
				{% if book.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page=1">Бірінші</a>
					</li>								
					<li class="page-item">
						<a class="page-link" href="?page={{ book.previous_page_number }}">Алдыңғы</a>
					</li>
				{% endif %}
				{% for ord in book.paginator.page_range %}
					{% if book.number == ord %}
						<li class="page-item active">
							<span class="page-link">{{ ord }}
								<span class="sr-only">(current)</span>
							</span>
						</li>
					{% elif ord > book.number|add:'-3' and ord < book.number|add:'3' %}
						<li class="page-item">
							<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
						</li>

					{% endif %}

				{% endfor %}
				 {% if book.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ book.next_page_number }}">Келесі/a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ book.paginator.num_pages }}">Алдыңғы</a>
					</li>
				{% endif %}
			    </ul>
			</div>
			{% else %}
			<h3 class="text-center mt-5">Тауар табылмады</h3>
			{% endif %}	

{% endblock %}

BookShop/store/templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block headermenu %}
<div class="header-bottom">
	<div class="container-fluid">
		<div class="row">
			
		</div>
	</div>
</div>
{% endblock %}

			{% block container %}
			<div class="row">
				<div class="col-sm-12">
					<div style="margin:0 auto; width: 700px;">
						<ul id="demo3">
							{% for sld in slide %}
							<li><img height="10" src="{{ sld.slideimg.url }}"/></li>
							{% endfor %}
						</ul>
					</div>
				</div>

				<div class="col-sm-12">
					<div class="titleheader">
						<h3 class="h2header text-center">Жаңа жарияланған тауарлар</h3>
						
					</div>
					<div class="regulara sliderzx">
						{% for item in newbooks %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ item.coverpage.url }}"/>
							</div>
							<a href="{% url 'store:book' id=item.id %}">{{ item.name|text_short }}</a>
							<a href="{% url 'store:writer' id=item.writer.id %}">{{ item.writer }}</a>
							<div class="rating">
								{{ item.totalrating|averagerating:item.totalreview }}
								<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
							</div>
							<p> {{ item.price }} $</p>
							<button class="btn btn-warning" id="addTocart" data-book-id="{{ item.id }}">
									<i class="fa fa-shopping-cart"></i> Себетке қосу
								</button>
						</div>
						{% endfor %}
					</div>
				</div>

			</div> 
			{% endblock %}

BookShop/store/templates/store/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Жүйеге кіру</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>


<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-md-4 col-sm-3">
			<div class="signin-form">
				{% if messages %}
				<div class="messages">
				    {% for message in messages %}
				    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
				    {% endfor %}
				</div>
				{% endif %}
				<h3> Жүйеге кіру</h3>	
				<form action="" method="POST" class="auth-validate-form">
					{% csrf_token %}
					<div class="form-group">
					   <label>Логин</label>
					   <input type="text" name="user" class="form-control">
					</div>
					<div class="form-group">
					   <label>Құпиясөз</label>
					   <input type="password" name="pass" class="form-control">
					</div>
					<button type="submit" class="btn btn-warning">Кіру</button>
				</form>
				
				<div class="a-divider-break"><h5>Аккаунт жоқ па?</h5></div>
				<a class="btn btn-default" href="{% url 'store:registration' %}">Аккаунт ашу</a>
			</div> 
		</div>
	</div>
</div>

</body>
</html>

BookShop/store/templates/store/show_data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>қолданбалы бағдарламалау интерфейсі</title>
</head>
<body>
    <h1>Портфолио пайдаланушылары</h1>
    {% for d in data %} 

    {{d}}<br>

    {% endfor %}
</body>
</html>

BookShop/store/templates/store/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>Жүйеге тіркелу</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-md-4 col-sm-3">
			<div class="signup-form">
				<div class="messages"></div>	
				<h3>Аккаунт ашу</h3>	
				<form action="" method="POST" class="auth-validate-form">
					{% csrf_token %}
					{% for field in form %}
					    <div class="form-group registration-form">
					        {{ field.label_tag }}<br>
					        {{ field }}

					        {% if field.help_text %}{% endif %}

					        {% for error in field.errors %}
					          <p style="color: red;font-size: 13px">{{ error }}</p>
					        {% endfor %}
					    </div>
					{% endfor %}
					<button class="btn btn-warning">Аккаунт ашу</button>
				</form>
				<div class="a-divider-break"></div>
				<div class="a-divider-inner">
					<div class="a-row">
					   Сізде аккаунт бар ма?
					    <a class="a-link-emphasis" href="{% url 'store:signin' %}"><i class='fa fa-caret-right'></i> Sign in</a>
					</div>						
				</div>
			</div> 
		</div>
	</div>
</div>
</body>
</html>

BookShop/store/templates/store/writer.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block container %}
			<div class="row">
				<div class="col-sm-12">
					<div class="row">
						<div class="col-sm-3">
							<div class="view-details">
								<img src="{{ wrt.pic.url }}">
							</div>
						</div>
						
						<div class="col-sm-8">
							<div class="product-information">
								<h3>{{ wrt.name }}</h3>
								<article class="text-justify" style="margin-top:10px;">{{ wrt.bio }}</article>

							</div>
						</div>
					</div>	
				</div>

				<div class="col-sm-12">
					<div class="titleheader">
						<h3 class="h2header text-center">Жарияланған тауарлар</h3>
					</div>
					<div class="regulara sliderzx">
						{% for item in book %}
						<div class="book-wrapper text-center">
							<div class="coverpage">
								<img src="{{ item.coverpage.url }}"/>
							</div>
							<a href="{% url 'store:book' id=item.id %}">{{ item.name|text_short }}</a>
							<a href="{% url 'store:writer' id=item.writer.id %}">{{ item.writer }}</a>
							<div class="rating">
								{{ item.totalrating|averagerating:item.totalreview }}
								<span class="totalrating">{{ item.totalreview|add:-1 }}</span>
							</div>
							<p> ${{ item.price }} </p>
							<button class="btn btn-warning" id="addTocart" data-book-id="{{ item.id }}">
									<i class="fa fa-shopping-cart"></i>Себетке қосу
								</button>


						</div>
						{% endfor %}
					</div>
				</div>
			</div>
{% endblock %}