BookShop/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from store.views import UserList,UserRUD

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('',include("store.urls")),
    path('users/',UserList.as_view()),
    path('user/<int:pk>',UserRUD.as_view()),

   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:bookid>', views.cart_add, name='cart_add'),
	path('remove/<int:bookid>', views.cart_remove, name='cart_remove'),
	path('update/<int:bookid>/<int:quantity>', views.cart_update, name='cart_update'),
]

BookShop/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
	path('', views.order_list, name="order_list"),
	path('<int:id>', views.order_details, name="order_details"),
	path('shipping/', views.order_create, name="order_create"),
	path('pdf/<int:id>',views.pdf.as_view(), name="pdf"),
]

BookShop/store/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns




app_name = 'store'

urlpatterns = [
	path('', views.index, name = "index"),
	path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),
	path('book/<int:id>', views.get_book, name="book"),
	path('books', views.get_books, name="books"),
	path('category/<int:id>', views.get_book_category, name="category"),
	path('writer/<int:id>', views.get_writer, name = "writer"),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>', views.UserDetail.as_view()),
    path('bookdetail/', views.BookDetail.as_view(), name='book_list'),
    path('receive_message/', views.receive_message, name='receive_message'),
    


    

]

urlpatterns = format_suffix_patterns(urlpatterns)

BookShop/order/models.py
from django.db import models
from store.models import Book
from django.contrib.auth.models import User


class Order(models.Model):
	customer = models.ForeignKey(User, on_delete = models.CASCADE)
	name = models.CharField(max_length=30)
	email = models.EmailField()
	phone = models.CharField(max_length=16)
	address = models.CharField(max_length=150)
	division = models.CharField(max_length=20)
	district = models.CharField(max_length=30)
	zip_code = models.CharField(max_length=30)
	payment_method = models.CharField(max_length = 20)
	account_no = models.CharField(max_length = 20)
	transaction_id = models.IntegerField()
	payable = models.IntegerField()
	totalbook = models.IntegerField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created', )

	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

BookShop/order/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
	DIVISION_CHOICES = (
		('Almaty', 'Almaty'),
		('Astana', 'Astana'),
		('Shymkent', 'Shymkent'),
	)

	"""DISCRICT_CHOICES = (
		('Almaty', 'Almaty'), 
		('Gazipur', 'Gazipur'),
		('Narayanganj', 'Narayanganj'),
	)"""

	PAYMENT_METHOD_CHOICES = (
		('Kaspi', 'Kaspi'),
		('Halyk','Halyk')
	)

	division = forms.ChoiceField(choices=DIVISION_CHOICES)
	# district =  forms.ChoiceField(choices=DISCRICT_CHOICES)
	payment_method = forms.ChoiceField(choices=PAYMENT_METHOD_CHOICES, widget=forms.RadioSelect())

	class Meta:
		model = Order
		fields = ['name', 'email', 'phone', 'address', 'division', 'district', 'zip_code', 'payment_method', 'account_no', 'transaction_id']

BookShop/order/views.py
from django.shortcuts import HttpResponse, render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.views import View
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from cart.cart import Cart
from .models import Order, OrderItem
from .forms import OrderCreateForm
from .pdfcreator import renderPdf

def order_create(request):
	cart = Cart(request)
	if request.user.is_authenticated:
		customer = get_object_or_404(User, id=request.user.id)
		form = OrderCreateForm(request.POST or None, initial={"name": customer.first_name, "email": customer.email})
		if request.method == 'POST':
			if form.is_valid():
				order = form.save(commit=False)
				order.customer = User.objects.get(id=request.user.id)
				order.payable = cart.get_total_price()
				order.totalbook = len(cart) # len(cart.cart) // number of individual book
				order.save()

				for item in cart:
					OrderItem.objects.create(
						order=order, 
						book=item['book'], 
						price=item['price'], 
						quantity=item['quantity']
						)
				cart.clear()
				return render(request, 'order/successfull.html', {'order': order})

			else:
				messages.error(request, "Fill out your information correctly.")

		if len(cart) > 0:
			return render(request, 'order/order.html', {"form": form})
		else:
			return redirect('store:books')
	else:
		return redirect('store:signin')
			
def order_list(request):
	my_order = Order.objects.filter(customer_id = request.user.id).order_by('-created')
	paginator = Paginator(my_order, 5)
	page = request.GET.get('page')
	myorder = paginator.get_page(page)

	return render(request, 'order/list.html', {"myorder": myorder})

def order_details(request, id):
	order_summary = get_object_or_404(Order, id=id)

	if order_summary.customer_id != request.user.id:
		return redirect('store:index')

	orderedItem = OrderItem.objects.filter(order_id=id)
	context = {
		"o_summary": order_summary,
		"o_item": orderedItem
	}
	return render(request, 'order/details.html', context)

class pdf(View):
    def get(self, request, id):
        try:
            query=get_object_or_404(Order,id=id)
        except:
            Http404('Content not found')
        context={
            "order":query
        }
        article_pdf = renderPdf('order/pdf.html',context)
        return HttpResponse(article_pdf,content_type='application/pdf')

BookShop/order/templates/order/details.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% block container %}
			<div class="row">
				<div class="col-sm-8">
					<div class="cart_info">
					    <table class="table table-hover">
					        <thead class="text-center">
					            <tr>
					                <th scope="col">#</th>
					                <th scope="col" style="width: 250px">Name</th>
					                <th scope="col">Price</th>
					                <th scope="col" >Qty</th>
					                <th scope="col"> Sub-Total</th>
					            </tr>
					        </thead>
					        <tbody class="text-center">
					        	{% for item in o_item %}
					            <tr>
					                <td class="cart_coverpage"><a href=""><img src="{{ item.book.coverpage.url}}"></a></td>
					                <td><a href="{% url 'store:book' id=item.book.id %}">{{ item.book.name }}</a></td>
					                <td class="cart_quantity">{{ item.book.price }} $.</td>
					                <td class="cart_quantity">{{ item.quantity }}</td>
					                <td>{{ item.book.price|subtotal:item.quantity }} $.</td>
					            </tr>
					            {% endfor %}
					        </tbody>
					    </table>
					</div>
				</div>
				<div class="col-sm-4">
					<ul class="list-group">
						<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Summary</h4></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Books<span>{{ o_summary.totalbook }}</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Subtotal<span>{{ o_summary.payable }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Shipping<span>{{ 50 }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Payable Total<span>{{ o_summary.payable|add:50 }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Order Data<span>{{ o_summary.created }}</span></li>
					</ul>
				</div>
			</div>
		{% endblock %}

BookShop/order/templates/order/list.html
{% extends 'store/base.html' %}
{% load static %}
{% block container %}
			<div class="cart_info">
			    <table class="table table-hover">
			        <thead class="text-center">
			            <tr>
			                <th scope="col">#</th>
			                <th scope="col">Order ID</th>
			                <th scope="col">Payment</th>
			                <th scope="col">Qty</th>
			                <th scope="col">Status</th>
			                <th scope="col">Date</th>
			            </tr>
			        </thead>
			        <tbody class="text-center">
			            {% for morder in myorder %}
			            <tr>
			                <td>{{ forloop.counter }}</td>
			                <td><a href="{% url 'order:order_details' id=morder.id %}">#0000{{ morder.id }}</a></td>
			                <td>{{ morder.payable }} $.</td>
			                <td>{{ morder.totalbook }}</td>
			                <td class="text-center">
			                	{% if morder.paid == True %}
			                	<p class="status3">Confirmed</p>
			                	{% else %}
			                	<p class="status1">Processing</p>
			                	{% endif %}
			                </td>
			                <td>{{ morder.created }}</td>
			            </tr>
			        	{% endfor %}
			        </tbody>
			    </table>
			</div>

			<div class="d-pagination">
			    <ul class="pagination">
				{% if myorder.has_previous %}
					<li class="page-item">
						<a class="page-link" href="?page=1">First</a>
					</li>								
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.previous_page_number }}">Previous</a>
					</li>
				{% endif %}
				{% for ord in myorder.paginator.page_range %}
					{% if myorder.number == ord %}
						<li class="page-item active">
							<span class="page-link">{{ ord }}
								<span class="sr-only">(current)</span>
							</span>
						</li>
					{% elif ord > myorder.number|add:'-3' and ord < myorder.number|add:'3' %}
						<li class="page-item">
							<a class="page-link" href="?page={{ ord }}">{{ ord }}</a>
						</li>

					{% endif %}

				{% endfor %}
				 {% if myorder.has_next %}
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.next_page_number }}">Next</a>
					</li>
					<li class="page-item">
						<a class="page-link" href="?page={{ myorder.paginator.num_pages }}">Last</a>
					</li>
				{% endif %}
			    </ul>
			</div>

		{% endblock %}

BookShop/order/templates/order/order.html
{% extends 'store/base.html' %}
{% load static %}
{% load customfunction %}
{% load crispy_forms_tags %}

{% block container %}
			<div class="row">
			    <div class="col-md-8 order-md-1 cart_info">
			        <h4 class="mb-3 mt-3">Shipping Address</h4>
					{% if messages %}
					<div class="messages">
					    {% for message in messages %}
					    <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
					    {% endfor %}
					</div>
					{% endif %}
			        <form action="" method="POST" class="needs-validation" novalidate="">
			        	{% csrf_token %}
			            <div class="row">
			                <div class="col-md-6 mb-3">
			                    {{ form.name|as_crispy_field }}
			                </div>
			                <div class="col-md-6 mb-3">
			                  
			                   	{{ form.email|as_crispy_field }}
			                </div>
			            </div>
	           			<div class="mb-3">
			                {{ form.phone|as_crispy_field }}
			            </div>

			            <div class="mb-3">
			                {{ form.address|as_crispy_field }}
			            </div>
			            <div class="row">
			                <div class="col-md-5 mb-3">
								{{ form.division|as_crispy_field }}
			                </div>
			                <div class="col-md-4 mb-3">
								{{ form.district|as_crispy_field }}
			                </div>
			                <div class="col-md-3 mb-3">
			                	{{ form.zip_code|as_crispy_field }}
			                </div>
			            </div>
			            <hr class="mb-4">
			            <div class="d-block my-3">
							{{ form.payment_method|as_crispy_field }}
			            </div>
			            <div class="row">
			                <div class="col-md-6 mb-3">
			                    {{ form.account_no|as_crispy_field }}
			                  
			                </div>
			                <div class="col-md-6 mb-3">
			                    {{ form.transaction_id|as_crispy_field }}
			                </div>
			            </div>
			            <hr class="mb-4">
			            <button class="btn btn-warning btn-block" type="submit" style="margin-bottom: 20px">Continue to checkout</button>
			        </form>
			    </div>
			    <div class="col-md-4 order-md-2 mb-4">
					<ul class="list-group">
						<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Checkout Summary</h4></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Books<span>{{ cart|length }}</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Subtotal<span>{{ cart.get_total_price }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Shipping<span>{{ cost|shipping }} $.</span></li>
						<li class="list-group-item d-flex justify-content-between align-items-center">Payable Total<span>{{ cart.get_total_price|payabletotal}} $.</span></li>
					</ul>
			    </div>
			</div>
		{% endblock %}

BookShop/order/templates/order/pdf.html
<!DOCTYPE html>
<html>
<head>
	<title>Book Store Sign In</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body>
	<div class="container">
		<div class="row justify-content-md-center">
	        <div class="col-md-12 cart_info">
		        <div class="ordered-info">
		                <h1>OrderID: #2018{{ order.id }}</h1>
		                <h1>Book: {{ order.totalbook }}</h1>
		                <h1>Name: {{ order.name }}</h1>
		                <h1>Phone: {{ order.phone }}</h1>
		                <h1>Email: {{ order.email }}</h1>
		                <h1>Account No: {{ order.account_no }}</h1>
		                <h1>Payment Method: {{ order.payment_method }}</h1>
		                <h1>Shipping address: {{ order.division }}:{{ order.zip_code }}, {{ order.district }}, {{ order.address }}</h1>
		        </div>
	        </div>
		</div>
	</div> 
</body>
</html>

BookShop/order/templates/order/successfull.html
{% extends 'store/base.html' %}
{% load static %}

{% block container %}
        <div class="row">
            <div class="col-md-12 cart_info">
                    <div class="successful-order text-center">
                        <i class="fa fa-check"></i>
                        <h3 class="page-header">Thank you for you purchase!</h3>
                    </div>
                    <div class="ordered-info">
                        <h5>OrderID: <span>#2018{{ order.id }}</span></h5>
                        <h5>Book: <span>{{ order.totalbook }}</span></h5>
                        <h5>Name: <span>{{ order.name }}</span></h5>
                        <h5>Phone: <span>{{ order.phone }}</span></h5>
                        <h5>Email: <span>{{ order.email }}</span></h5>
                        <h5>Account No: <span>{{ order.account_no }}</span></h5>
                        <h5>Payment Method: <span>{{ order.payment_method }}</span></h5>
                        <h5>Shipping address: <span>{{ order.division }}:{{ order.zip_code }}, {{ order.district }}, {{ order.address }}</span></h5>
                    </div>
                    <div class="download-info">
                        <a href="{% url 'order:pdf' id=order.id %}"><i class="fa fa-download" aria-hidden="true"></i></a>
                    </div>
            </div>
        </div>
{% endblock %}