BookShop/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from store.views import UserList,UserRUD

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('search/', include('search.urls')),
    path('order/', include('order.urls')),
    path('',include("store.urls")),
    path('users/',UserList.as_view()),
    path('user/<int:pk>',UserRUD.as_view()),

   
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_details, name='cart_details'),
	path('summary', views.cart_summary, name='cart_summary'),
	path('totalcart', views.total_cart, name='totalcart'),
	path('add/<int:bookid>', views.cart_add, name='cart_add'),
	path('remove/<int:bookid>', views.cart_remove, name='cart_remove'),
	path('update/<int:bookid>/<int:quantity>', views.cart_update, name='cart_update'),
]

BookShop/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
	path('', views.order_list, name="order_list"),
	path('<int:id>', views.order_details, name="order_details"),
	path('shipping/', views.order_create, name="order_create"),
	path('pdf/<int:id>',views.pdf.as_view(), name="pdf"),
]

BookShop/store/urls.py
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns




app_name = 'store'

urlpatterns = [
	path('', views.index, name = "index"),
	path('login', views.signin, name="signin"),
	path('logout', views.signout, name="signout"),
	path('registration', views.registration, name="registration"),
	path('book/<int:id>', views.get_book, name="book"),
	path('books', views.get_books, name="books"),
	path('category/<int:id>', views.get_book_category, name="category"),
	path('writer/<int:id>', views.get_writer, name = "writer"),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>', views.UserDetail.as_view()),
    path('bookdetail/', views.BookDetail.as_view(), name='book_list'),
    path('receive_message/', views.receive_message, name='receive_message'),
    


    

]

urlpatterns = format_suffix_patterns(urlpatterns)

BookShop/cart/models.py
from django.db import models

# Create your models here.

BookShop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Book, Category
from .cart import Cart

def cart_add(request, bookid):
	cart = Cart(request)  
	book = get_object_or_404(Book, id=bookid) 
	cart.add(book=book)

	return redirect('store:index')

def cart_update(request, bookid, quantity):
	cart = Cart(request) 
	book = get_object_or_404(Book, id=bookid) 
	cart.update(book=book, quantity=quantity)
	price = (book.price*quantity)

	return render(request, 'cart/price.html', {"price":price})

def cart_remove(request, bookid):
    cart = Cart(request)
    book = get_object_or_404(Book, id=bookid)
    cart.remove(book)
    return redirect('cart:cart_details')

def total_cart(request):
	return render(request, 'cart/totalcart.html')

def cart_summary(request):

	return render(request, 'cart/summary.html')

def cart_details(request):
	cart = Cart(request)
	context = {
		"cart": cart,
	}
	return render(request, 'cart/cart.html', context)

BookShop/cart/templates/cart/cart.html
{% extends 'store/base.html' %}

			{% block container %}
			<div class="row">
				<div class="col-sm-8">
					<div class="cart_info">
					    <table class="table table-hover">
					        <thead class="text-center">
					            <tr>
					                <th scope="col">#</th>
					                <th scope="col" style="width: 250px">Name</th>
					                <th scope="col" style="width: 250">Qty</th>
					                <th scope="col">Price</th>
					                <th scope="col">Action</th>
					            </tr>
					        </thead>
					        <tbody class="text-center">
					        {% for item in cart %}
					        	{% with book=item.book %}
				           		 <tr>
					                <td class="cart_coverpage"><a href=""><img src="{{ book.coverpage.url }}"></a></td>
					                <td>{{ book.name }}</td>
					                <td class="cart_quantity"><input type="text" name="qty" value="{{ item.quantity }}" onchange ="updateCartItem(this,{{ book.id }})" style="width: 30px"></td>
					                <td id="{{ book.id }}">{{ item.total_price }} $.</td>
					                <td><a href="{% url 'cart:cart_remove' bookid=book.id %}" class="btn btn-danger"><i class="fa fa-trash-o"></i></a></td>
					            </tr>
					            {% endwith %}
					        {% endfor %}
					        </tbody>
					    </table>
						<div class="continue_or_next text-center">
							<a href="{% url 'store:index' %}" class="btn _to_shope">Continue to Shope</a>
							<a href="{% url 'order:order_create' %}" class="btn _to_continue">Proceed to Checkout</a>
						</div>
					</div>
				</div>
				<div class="col-sm-4" id="abc">

				</div>
			</div> 
			{% endblock %}


{% block scripts %}
	<script type="text/javascript">

	$(document).ready(function(){
		summary();
 
	}); 
	function summary(){
		$.ajax({
			url : "summary",
			type : "GET",
			success : function(data){
				$("#abc").html(data);
			}
		})
	}
	function updateCartItem(obj,id){
		$.ajax({
			url: "update/"+id+"/"+obj.value,
			type: "GET",
			data: {
				bookid: id,
				quantity: obj.value
			},
			success	:function(data){
				$("#"+(id.toString())).html(data);
				summary();
				totalCart();
			}
		})
	}

	</script>
{% endblock %}

BookShop/cart/templates/cart/price.html
{{ price }} $.

BookShop/cart/templates/cart/summary.html
{% load customfunction %}
<ul class="list-group">
	<li class="list-group-item d-flex justify-content-between align-items-center"><h4>Checkout Summary</h4></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Books<span>{{ cart|length }}</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Subtotal<span>{{ cart.get_total_price }} $.</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Shipping<span>{{ cost|shipping }} $.</span></li>
	<li class="list-group-item d-flex justify-content-between align-items-center">Payable Total<span>{{ cart.get_total_price|payabletotal}} $.</span></li>
</ul>	

BookShop/cart/templates/cart/totalcart.html
{{ cart|length }}